/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-16 03:49:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jsp11_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css1.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("      \n");
      out.write("        \n");
      out.write("        <br><br>\n");
      out.write("        \n");
      out.write("     <div class=\"container-lg\"><h1><center>Holaaaaa este es una calculadora</center></h1>\n");
      out.write("         <div class=\"container-lg\"><h4><center>Esta calculadora se basa en calcular numeros aleatorios y determinar si son mayores o menores de numeros ya dados</center></h4>\n");
      out.write("            <div class=\"card\">\n");
      out.write("  <div class=\"card-body\">\n");
      out.write("    \n");
      out.write("\n");
      out.write("        ");

            int x = (int)((Math.random() * 100));
            if(x < 100)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 100</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 100</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 1 es: ");
      out.print(x);
      out.write("</h1>\n");
      out.write("       \n");
      out.write("          </div>\n");
      out.write("</div>\n");
      out.write("        \n");
      out.write("             <br><br><br>\n");
      out.write("        <div class=\"card\">\n");
      out.write("  <div class=\"card-body\">\n");
      out.write("\n");
      out.write("         ");

            int r = (int)((Math.random() * 100));
            if(r < 95)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 95</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 95</h1><br>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 2 es: ");
      out.print(r);
      out.write("</h1>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("        <br><br><br>\n");
      out.write("        \n");
      out.write("  <div class=\"card\">\n");
      out.write("  <div class=\"card-body\">\n");
      out.write("    \n");
      out.write("        \n");
      out.write("         ");

            int e = (int)((Math.random() * 100));
            if(e < 90)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 90</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 90</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 3 es: ");
      out.print(e);
      out.write("</h1>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("  <br><br><br>\n");
      out.write("  <div class=\"card\">\n");
      out.write("  <div class=\"card-body\">\n");
      out.write("    \n");
      out.write("        \n");
      out.write("         ");

            int h = (int)((Math.random() * 100));
            if(h < 80)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 80</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 80</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 4 es: ");
      out.print(h);
      out.write("</h1>\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("     <br><br><br>\n");
      out.write("    <div class=\"card\">\n");
      out.write("  <div class=\"card-body\">\n");
      out.write("    \n");
      out.write("        \n");
      out.write("         ");

            int j = (int)((Math.random() * 100));
            if(j < 70)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 70</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 70</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 5 es: ");
      out.print(j);
      out.write("</h1>\n");
      out.write("     </div>\n");
      out.write("    </div> \n");
      out.write("     <br><br>\n");
      out.write("     \n");
      out.write("     \n");
      out.write("     <div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\n");
      out.write("  <div class=\"accordion-item\">\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingOne\">\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\" aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\n");
      out.write("        Ver el numero 6\n");
      out.write("      </button>\n");
      out.write("    </h2>\n");
      out.write("    <div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("      <div class=\"accordion-body\">\n");
      out.write("          \n");
      out.write("     ");

            int k = (int)((Math.random() * 100));
            if(k < 60)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 60</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 60</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 6 es: ");
      out.print(k);
      out.write("</h1>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"accordion-item\">\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingTwo\">\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwo\">\n");
      out.write("        Ver el numero 7\n");
      out.write("      </button>\n");
      out.write("    </h2>\n");
      out.write("    <div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("      <div class=\"accordion-body\">\n");
      out.write("          \n");

            int l = (int)((Math.random() * 100));
            if(l < 50)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 50</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 50</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 7 es: ");
      out.print(l);
      out.write("</h1>\n");
      out.write("       \n");
      out.write("      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"accordion-item\">\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingThree\">\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseThree\" aria-expanded=\"false\" aria-controls=\"flush-collapseThree\">\n");
      out.write("       Ver el numero 8\n");
      out.write("      </button>\n");
      out.write("    </h2>\n");
      out.write("    <div id=\"flush-collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingThree\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("      <div class=\"accordion-body\">\n");
      out.write("          \n");

            int n = (int)((Math.random() * 100));
            if(n < 40)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 40</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 40</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 8 es: ");
      out.print(n);
      out.write("</h1>\n");
      out.write("      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <div class=\"accordion-item\">\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingFour\">\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseFour\" aria-expanded=\"false\" aria-controls=\"flush-collapseFour\">\n");
      out.write("        Ver el numero 9\n");
      out.write("      </button>\n");
      out.write("    </h2>\n");
      out.write("    <div id=\"flush-collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingFour\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("      <div class=\"accordion-body\">\n");
      out.write("          \n");
      out.write("     ");

            int p = (int)((Math.random() * 100));
            if(p < 30)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 30</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 30</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 9 es: ");
      out.print(p);
      out.write("</h1>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <div class=\"accordion-item\">\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingFive\">\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseFive\" aria-expanded=\"false\" aria-controls=\"flush-collapseFive\">\n");
      out.write("        Ver el numero 10\n");
      out.write("      </button>\n");
      out.write("    </h2>\n");
      out.write("    <div id=\"flush-collapseFive\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingFive\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("      <div class=\"accordion-body\">\n");
      out.write("          \n");
      out.write("     ");

            int z = (int)((Math.random() * 100));
            if(z < 20)
            {
        
      out.write("\n");
      out.write("        <h1>Es menor a 20</h1>\n");
      out.write("        ");

            }
            else
            {
       
      out.write("\n");
      out.write("       <h1>Es mayor o igual a 20</h1>\n");
      out.write("       ");
 
           }       
        
      out.write("\n");
      out.write("        <h1>El numero 10 es: ");
      out.print(z);
      out.write("</h1>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("     \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("</div>\n");
      out.write("     <br><br><br><br><br><br>\n");
      out.write("     \n");
      out.write("     \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
